### ISSUE TITLE
FIXED: FABRIC API NEEDED

### ISSUE THREAD

**Issue by gorro123** [comp500/tinymap#2]
I have this "issue" with every map plugin, so I guess its me and maybe not you.
However I can't start my server with map plugins on
`● minecraft.service - Minecraft Server
     Loaded: loaded (/etc/systemd/system/minecraft.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Wed 2021-02-24 11:49:39 CET; 7s ago
    Process: 11553 ExecStart=/usr/bin/java -Xmx57344M -Xms57344M -jar fabricstart.jar nogui (code=exited, status=1/FAILURE)
    Process: 11599 ExecStop=/opt/minecraft/tools/mcrcon/mcrcon -H 127.0.0.1 -P 25575 -p [REDACTED] stop (code=exited, status=1/FAILURE)
   Main PID: 11553 (code=exited, status=1/FAILURE)

Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabricstart.jar:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabricstart.jar:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal java[11553]:         at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabricstart.jar:?]
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal mcrcon[11599]: Connection failed.
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal mcrcon[11599]: Error 111: Connection refused
Feb 24 11:49:39 Ubuntu-2004-focal-64-minimal systemd[1]: minecraft.service: Succeeded.
`

**Comment by gorro123** [comment]
My server runs on Java 14, fabric 1.16.5 and has lithium and phosphor installed

**Comment by gorro123** [comment]
`[11:49:39] [main/INFO]: Loading for game Minecraft 1.16.5
[11:49:39] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'BlueMap' (bluemap) requires any version of mod fabric, which is missing!
	 - You must install any version of fabric.
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:322) ~[fabricstart.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabricstart.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabricstart.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabricstart.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabricstart.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabricstart.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabricstart.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabricstart.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabricstart.jar:?]
`

**Comment by gorro123** [comment]
is the fabric API needed?
